export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ProductLayout({ children }) {
  return (
    <div className="w-full h-auto flex flex-col">
      {children}
    </div>
  )
}
